# Generated by Django 5.2 on 2025-04-12 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=100)),
                ('teacher_email', models.CharField(max_length=100)),
                ('classdiv', models.CharField(max_length=100)),
                ('subject_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('subject_marks', models.IntegerField()),
                ('total_marks', models.IntegerField()),
                ('subject_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smdapp.subjectmetadata')),
            ],
        ),
    ]
