# Generated by Django 5.2 on 2025-04-12 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smdapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjectmetadata',
            old_name='classdiv',
            new_name='class_name',
        ),
        migrations.AddField(
            model_name='subjectmetadata',
            name='division',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
